    # PMF modeling results analysis
    1. Basic formula check: X = G * P + R

In [1]:
import pandas as pd

X = pd.read_csv('Siheung_Conc_kNN_051921.csv')
X = X[['date', 'PM2.5', 'NO3-', 'SO42-', 'NH4+', 'K+', 'Na+', 'Cl-', 'OC',
       'EC', 'Mg', 'Si', 'Ca', 'Ti', 'V', 'Mn', 'Fe', 'Ni', 'Cu', 'Zn', 'As',
       'Pb']]
print(X)

           date      PM2.5       NO3-     SO42-       NH4+        K+  \
0    11/16/2019  36.186500  10.519697  3.070176   4.615067  0.292758
1    11/19/2019  13.795987   1.650593  1.645891   0.998299  0.099412
2    11/22/2019  31.454419   8.268086  1.724467   2.844703  0.270033
3    11/26/2019  25.748086   6.717402  1.969101   2.914216  0.191162
4    11/30/2019  40.446304  13.521696  1.797991   4.768353  0.415744
..          ...        ...        ...       ...        ...       ...
116  11/24/2020  15.595000   7.345296  1.999587   2.823678  0.295429
117  11/26/2020  42.746000  32.898342  6.857061  10.924650  0.752566
118  11/30/2020  19.903000  10.806479  3.800149   4.462531  0.416710
119   12/2/2020  17.280000  31.231501  8.116521  12.034841  0.525552
120   12/6/2020  42.781000   6.381265  2.403858   2.640202  0.404271

          Na+       Cl-         OC        EC  ...        Ca        Ti  \
0    0.194727  0.845747   9.247382  1.177020  ...  0.067338  0.011543
1    0.187291  0.116985   3.331602  0.528025  ...  0.134763  0.012723
2    0.105607  0.315484   9.912487  1.908402  ...  0.233437  0.020110
3    0.085555  0.657704   7.052623  1.331131  ...  0.061571  0.009189
4    0.139027  1.138951  11.429528  1.536803  ...  0.127842  0.019549
..        ...       ...        ...       ...  ...       ...       ...
116  0.136830  0.478906   5.845661  0.997388  ...  0.074426  0.010044
117  0.220794  1.523791  10.588990  1.576165  ...  0.090983  0.017350
118  0.183477  0.565980   5.650279  0.883609  ...  0.065652  0.006529
119  0.270551  3.265267   6.061994  0.944623  ...  0.126237  0.010200
120  0.314088  0.429149   9.980422  0.920737  ...  0.047424  0.007249

            V        Mn        Fe        Ni        Cu        Zn        As  \
0    0.000854  0.020004  0.304653  0.001473  0.008279  0.054187  0.000712
1    0.000492  0.017377  0.235235  0.001179  0.001668  0.046186  0.004331
2    0.000555  0.022091  0.443069  0.001095  0.005328  0.047591  0.002543
3    0.000513  0.016355  0.224539  0.001116  0.008133  0.063110  0.004803
4    0.001409  0.029095  0.457959  0.002170  0.006560  0.090531  0.012667
..        ...       ...       ...       ...       ...       ...       ...
116  0.000209  0.023733  0.267098  0.001243  0.003228  0.063949  0.006267
117  0.000319  0.031003  0.374063  0.001060  0.003854  0.095318  0.020996
118  0.000219  0.016922  0.192359  0.000810  0.001979  0.046228  0.013736
119  0.000350  0.014614  0.190218  0.000721  0.001875  0.049732  0.009036
120  0.000101  0.017768  0.216489  0.001159  0.020082  0.127073  0.004022

           Pb
0    0.013999
1    0.021339
2    0.019609
3    0.027526
4    0.082001
..        ...
116  0.028517
117  0.045648
118  0.036560
119  0.032173
120  0.035777

[121 rows x 22 columns]

In [2]:
G1 = pd.read_csv('210525q5_contributions1_(avg = 1).csv')
print('G1 (avg = 1)')
print(G1)
print('\n')
G2 = pd.read_csv('210525q5_contributions2_(conc. units, Total Variable PM2.5).csv')
print('G2 (conc. units, Total Variable PM2.5)')
print(G2)

G1 (avg = 1)
           date  Factor 1  Factor 2  Factor 3  Factor 4  Factor 5
0      11/16/19    0.6130     1.860    -0.200     0.902     2.560
1      11/19/19   -0.0634     1.660     1.330     0.342     0.203
2      11/22/19   -0.0607     2.860     0.987     0.161     1.360
3      11/26/19    1.1100     1.360     0.788     0.318     1.620
4      11/30/19    0.5750     2.390     2.310    -0.200     2.990
..          ...       ...       ...       ...       ...       ...
116    11/24/20    0.2680     1.290     1.680     0.208     1.470
117    11/26/20   -0.0549     0.835     3.740     1.280     5.240
118    11/30/20    0.0241     0.611     2.830     0.740     1.890
119  2012-02-20   -0.2000     0.233     2.950     1.660     3.830
120  2012-06-20    3.2000     1.120     0.710     0.354     1.570

[121 rows x 6 columns]


G2 (conc. units, Total Variable PM2.5)
           date  Factor 1  Factor 2  Factor 3  Factor 4  Factor 5
0      11/16/19    0.8480     7.600    -0.497     5.400     15.20
1      11/19/19   -0.0877     6.810     3.310     2.040      1.21
2      11/22/19   -0.0839    11.700     2.450     0.965      8.08
3      11/26/19    1.5400     5.540     1.960     1.900      9.58
4      11/30/19    0.7940     9.780     5.730    -1.200     17.70
..          ...       ...       ...       ...       ...       ...
116    11/24/20    0.3710     5.270     4.170     1.240      8.74
117    11/26/20   -0.0758     3.420     9.280     7.650     31.10
118    11/30/20    0.0333     2.500     7.020     4.430     11.20
119  2012-02-20   -0.2760     0.952     7.330     9.940     22.70
120  2012-06-20    4.4300     4.570     1.760     2.120      9.32

[121 rows x 6 columns]

In [3]:
P1 = pd.read_csv('210525q5_profiles1_(conc. of species).csv')
P2 = pd.read_csv('210525q5_profiles2_(percent of species sum).csv')
P3 = pd.read_csv('210525q5_profiles3_(percent of total variable).csv')

print('P1 (conc. of species).')
print(P1)
print('\n')
print('P2 (percent of species sum)')
print(P2)
print('\n')
print('P3 (percent of total variable)')
print(P3)

P1 (conc. of species).
   species  Factor 1  Factor 2  Factor 3  Factor 4  Factor 5
0    PM2.5  1.380000  4.090000  2.480000  5.980000  5.930000
1     NO3-  0.000000  0.216000  0.000000  0.469000  4.340000
2    SO42-  0.083000  0.109000  0.536000  2.460000  0.314000
3     NH4+  0.000000  0.000000  0.231000  1.240000  1.540000
4       K+  0.000000  0.000000  0.107000  0.000000  0.084100
5      Na+  0.013600  0.056000  0.025600  0.019300  0.016700
6      Cl-  0.003400  0.000924  0.017000  0.020300  0.290000
7       OC  0.285000  3.180000  0.059000  0.527000  1.630000
8       EC  0.001560  0.423000  0.080300  0.000000  0.167000
9       Mg  0.003220  0.017300  0.013500  0.002250  0.000000
10      Si  0.002190  0.108000  0.056700  0.005190  0.020400
11      Ca  0.000000  0.029200  0.012800  0.001490  0.004650
12      Ti  0.000000  0.004300  0.001500  0.000517  0.001210
13       V  0.000016  0.000139  0.000000  0.000172  0.000000
14      Mn  0.002550  0.007930  0.001320  0.002120  0.001550
15      Fe  0.016400  0.108000  0.023200  0.017400  0.020500
16      Ni  0.000159  0.000551  0.000013  0.000365  0.000057
17      Cu  0.004440  0.001160  0.000000  0.000000  0.000642
18      Zn  0.027800  0.016900  0.008970  0.009110  0.002890
19      As  0.000815  0.000000  0.002510  0.000244  0.000577
20      Pb  0.005960  0.002280  0.009720  0.000390  0.003450


P2 (percent of species sum)
   species  Factor 1  Factor 2  Factor 3  Factor 4  Factor 5
0    PM2.5     6.960    20.600     12.50     30.10     29.80
1     NO3-     0.000     4.310      0.00      9.33     86.40
2    SO42-     2.370     3.120     15.30     70.20      8.98
3     NH4+     0.000     0.000      7.67     41.20     51.10
4       K+     0.000     0.000     55.90      0.00     44.10
5      Na+    10.300    42.700     19.50     14.70     12.70
6      Cl-     1.030     0.278      5.12      6.11     87.50
7       OC     5.010    55.900      1.04      9.27     28.80
8       EC     0.232    63.000     12.00      0.00     24.80
9       Mg     8.880    47.600     37.30      6.19      0.00
10      Si     1.130    56.200     29.40      2.69     10.60
11      Ca     0.000    60.600     26.60      3.10      9.64
12      Ti     0.000    57.100     20.00      6.87     16.10
13       V     4.860    42.600      0.00     52.60      0.00
14      Mn    16.500    51.200      8.51     13.70     10.00
15      Fe     8.830    58.200     12.50      9.37     11.10
16      Ni    13.900    48.200      1.10     31.90      4.97
17      Cu    71.100    18.600      0.00      0.00     10.30
18      Zn    42.400    25.700     13.70     13.90      4.40
19      As    19.600     0.000     60.60      5.87     13.90
20      Pb    27.300    10.500     44.60      1.79     15.80


P3 (percent of total variable)
   species  Factor 1  Factor 2   Factor 3  Factor 4   Factor 5
0    PM2.5       NaN       NaN        NaN       NaN        NaN
1     NO3-   0.00000   5.29000   0.000000   7.85000  73.200000
2    SO42-   6.01000   2.67000  21.600000  41.10000   5.300000
3     NH4+   0.00000   0.00000   9.320000  20.80000  26.000000
4       K+   0.00000   0.00000   4.300000   0.00000   1.420000
5      Na+   0.98000   1.37000   1.030000   0.32300   0.281000
6      Cl-   0.24600   0.02260   0.684000   0.33900   4.900000
7       OC  20.60000  77.70000   2.380000   8.81000  27.600000
8       EC   0.11300  10.30000   3.230000   0.00000   2.810000
9       Mg   0.23300   0.42200   0.545000   0.03750   0.000000
10      Si   0.15800   2.65000   2.280000   0.08680   0.343000
11      Ca   0.00000   0.71500   0.517000   0.02500   0.078400
12      Ti   0.00000   0.10500   0.060500   0.00865   0.020400
13       V   0.00115   0.00341   0.000000   0.00288   0.000000
14      Mn   0.18500   0.19400   0.053000   0.03540   0.026200
15      Fe   1.18000   2.64000   0.935000   0.29000   0.347000
16      Ni   0.01150   0.01350   0.000507   0.00610   0.000959
17      Cu   0.32100   0.02840   0.000000   0.00000   0.010800
18      Zn   2.01000   0.41300   0.361000   0.15200   0.048700
19      As   0.05900   0.00000   0.101000   0.00407   0.009730
20      Pb   0.43100   0.05570   0.392000   0.00652   0.058200

In [4]:
R1 = pd.read_csv('210525q5_residuals1_base.csv')
R2 = pd.read_csv('210525q5_residuals2_Scaled Residuals.csv')
print ('R1')
print(R1)
print('\n')
print ('R2')
print(R2)

R1
      Date_Time   PM2.5     NO3-   SO42-    NH4+       K+     Na+     Cl-  \
0      11/16/19   7.650  -1.4300 -0.0978 -0.4110  0.09860  0.0274  0.0833
1      11/19/19   0.522   0.2460 -0.1480 -0.0489 -0.05980  0.0509  0.0270
2      11/22/19   8.330   1.6500  0.0628  0.3130  0.05000 -0.1050 -0.1030
3      11/26/19   5.230  -0.7410  0.0170 -0.1550 -0.02880 -0.0587  0.1640
4      11/30/19   7.590   0.0991 -0.1980 -0.1310 -0.08230 -0.1080  0.2310
..          ...     ...      ...     ...     ...      ...     ...     ...
116    11/24/20  -4.200   0.5660 -0.0386 -0.0968 -0.00804 -0.0106  0.0160
117    11/26/20  -8.610   9.3500 -0.0242  0.3850 -0.08750 -0.0331 -0.0884
118    11/30/20  -5.300   2.1100 -0.1970 -0.0311 -0.04440  0.0306 -0.0473
119  2012-02-20 -23.400  13.8000  1.2400  3.3800 -0.11200  0.0886  2.0700
120  2012-06-20  20.600  -0.8570  0.2720 -0.3890  0.19600  0.1570 -0.0586

         OC      EC  ...       Ca        Ti         V        Mn       Fe  \
0   -1.4800 -0.0212  ...  0.00233  0.000288  0.000430 -0.001910  0.03040
1   -2.5300 -0.3160  ...  0.06750  0.003150  0.000202  0.001560  0.01570
2   -1.5400  0.3910  ...  0.13000  0.004590  0.000129 -0.004200  0.08140
3   -0.4280  0.4230  ...  0.00382  0.000058  0.000252 -0.001440  0.00303
4   -1.2600 -0.1610  ...  0.01460  0.002280  0.001100  0.001410  0.07880
..      ...     ...  ...      ...       ...       ...       ...      ...
116 -0.9440  0.0710  ...  0.00799  0.000088 -0.000011  0.007900  0.05070
117 -1.5100  0.0477  ... -0.00777  0.001130 -0.000017  0.008750  0.06810
118  0.0498  0.0819  ...  0.00153 -0.003020  0.000006  0.003790  0.00861
119 -1.9300 -0.0299  ...  0.06120 -0.000737  0.000035 -0.000078 -0.00772
120  2.7200  0.1240  ... -0.00222 -0.000709 -0.000167 -0.003390 -0.01150

           Ni        Cu       Zn        As        Pb
0   -0.000121  0.001750 -0.00810 -0.000984 -0.001140
1    0.000119 -0.000116  0.00419  0.000836  0.004150
2   -0.000622  0.001390 -0.01330 -0.000715 -0.000922
3   -0.000026  0.000584 -0.00535  0.000908  0.004460
4    0.000634 -0.000695  0.00660  0.004720  0.040400
..        ...       ...      ...       ...       ...
116  0.000310 -0.000408  0.01350  0.000922  0.002470
117 -0.000203 -0.000238  0.02240  0.008310 -0.010900
118  0.000056 -0.000053 -0.00235  0.005340  0.000699
119 -0.000237  0.000035 -0.00133 -0.000840 -0.009760
120 -0.000193  0.003540  0.00489 -0.001370  0.001690

[121 rows x 22 columns]


R2
      Date_Time  PM2.5   NO3-  SO42-   NH4+     K+    Na+    Cl-     OC  \
0      11/16/19  0.423 -0.403 -0.104 -0.272  1.020  0.520  0.290 -0.555
1      11/19/19  0.076  0.426 -0.273 -0.142 -1.390  0.711  0.430 -1.800
2      11/22/19  0.530  0.666  0.121  0.367  0.616 -1.990 -0.893 -0.540
3      11/26/19  0.406 -0.343  0.029 -0.171 -0.456 -1.570  0.830 -0.224
4      11/30/19  0.375  0.024 -0.341 -0.090 -0.583 -1.700  0.675 -0.397
..          ...    ...    ...    ...    ...    ...    ...    ...    ...
116    11/24/20 -0.487  0.257 -0.063 -0.112 -0.089 -0.245  0.112 -0.554
117    11/26/20 -0.373  0.947 -0.012  0.117 -0.360 -0.454 -0.186 -0.504
118    11/30/20 -0.481  0.650 -0.167 -0.023 -0.332  0.557 -0.264  0.034
119  2012-02-20 -1.760  1.470  0.508  0.936 -0.621  1.090  2.110 -0.985
120  2012-06-20  0.962 -0.411  0.377 -0.447  1.620  1.670 -0.417  1.070

        EC  ...     Ca     Ti      V     Mn     Fe     Ni     Cu     Zn  \
0   -0.060  ...  0.113  0.064  1.420 -0.297  0.332 -0.184  0.702 -0.452
1   -1.260  ...  1.660  0.655  0.959  0.295  0.221  0.211 -0.205  0.302
2    0.735  ...  1.860  0.678  0.571 -0.558  0.612 -0.931  0.865 -0.786
3    1.090  ...  0.203  0.015  1.170 -0.274  0.045 -0.046  0.239 -0.267
4   -0.341  ...  0.380  0.345  2.420  0.161  0.573  0.784 -0.328  0.243
..     ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
116  0.233  ...  0.353  0.021 -0.073  1.100  0.632  0.535 -0.380  0.702
117  0.106  ... -0.267  0.188 -0.099  0.937  0.606 -0.352 -0.194  0.783
118  0.297  ...  0.076 -0.777  0.044  0.736  0.148  0.117 -0.083 -0.164
119 -0.100  ...  1.610 -0.171  0.196 -0.017 -0.131 -0.468  0.059 -0.087
120  0.433  ... -0.146 -0.197 -0.751 -0.558 -0.171 -0.323  0.587  0.128

        As     Pb
0   -0.645 -0.221
1    0.492  0.598
2   -0.508 -0.139
3    0.499  0.514
4    1.180  1.630
..     ...    ...
116  0.419  0.275
117  1.300 -0.674
118  1.240  0.062
119 -0.269 -0.815
120 -0.722  0.152

[121 rows x 22 columns]

In [5]:
print(G1.iloc[:,1:])
print(P1.T.iloc[1:,0:])

     Factor 1  Factor 2  Factor 3  Factor 4  Factor 5
0      0.6130     1.860    -0.200     0.902     2.560
1     -0.0634     1.660     1.330     0.342     0.203
2     -0.0607     2.860     0.987     0.161     1.360
3      1.1100     1.360     0.788     0.318     1.620
4      0.5750     2.390     2.310    -0.200     2.990
..        ...       ...       ...       ...       ...
116    0.2680     1.290     1.680     0.208     1.470
117   -0.0549     0.835     3.740     1.280     5.240
118    0.0241     0.611     2.830     0.740     1.890
119   -0.2000     0.233     2.950     1.660     3.830
120    3.2000     1.120     0.710     0.354     1.570

[121 rows x 5 columns]
            0      1      2      3       4       5         6      7        8   \
Factor 1  1.38    0.0  0.083    0.0     0.0  0.0136    0.0034  0.285  0.00156
Factor 2  4.09  0.216  0.109    0.0     0.0   0.056  0.000924   3.18    0.423
Factor 3  2.48    0.0  0.536  0.231   0.107  0.0256     0.017  0.059   0.0803
Factor 4  5.98  0.469   2.46   1.24     0.0  0.0193    0.0203  0.527      0.0
Factor 5  5.93   4.34  0.314   1.54  0.0841  0.0167      0.29   1.63    0.167

               9   ...       11        12        13       14      15  \
Factor 1  0.00322  ...      0.0       0.0  0.000016  0.00255  0.0164
Factor 2   0.0173  ...   0.0292    0.0043  0.000139  0.00793   0.108
Factor 3   0.0135  ...   0.0128    0.0015       0.0  0.00132  0.0232
Factor 4  0.00225  ...  0.00149  0.000517  0.000172  0.00212  0.0174
Factor 5      0.0  ...  0.00465   0.00121       0.0  0.00155  0.0205

                16        17       18        19       20
Factor 1  0.000159   0.00444   0.0278  0.000815  0.00596
Factor 2  0.000551   0.00116   0.0169       0.0  0.00228
Factor 3  0.000013       0.0  0.00897   0.00251  0.00972
Factor 4  0.000365       0.0  0.00911  0.000244  0.00039
Factor 5  0.000057  0.000642  0.00289  0.000577  0.00345

[5 rows x 21 columns]

In [6]:
G1.iloc[:,1:] @ P1.T.iloc[1:,0:]

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,28.5321,11.935198,3.169179,5.01468,0.193896,0.167537,0.761113,10.725859,1.199196,0.033481,...,0.065,0.011262,0.000423,0.021929,0.274468,0.001594,0.006523,0.062297,0.001695,0.015134
1,13.249258,1.399978,1.79362,1.04393,0.159382,0.136136,0.089741,5.850325,0.842781,0.047238,...,0.06695,0.009555,0.000289,0.015797,0.219209,0.001058,0.001774,0.041924,0.003487,0.017168
2,23.088974,6.595669,1.658834,2.522037,0.219985,0.210421,0.416884,11.43738,1.516061,0.062969,...,0.102709,0.015507,0.000424,0.026277,0.361464,0.001715,0.003921,0.060897,0.003252,0.020507
3,20.55668,7.473702,1.953698,3.071148,0.220558,0.14462,0.494682,7.495828,0.910828,0.038456,...,0.057805,0.009155,0.000261,0.017841,0.222109,0.001144,0.007546,0.068489,0.003895,0.023089
4,32.8321,13.39904,1.993255,4.89021,0.498629,0.246869,0.906473,12.668665,1.69669,0.073933,...,0.112961,0.017257,0.000307,0.027679,0.378957,0.001534,0.007245,0.083916,0.007943,0.041567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,19.77328,6.755992,2.036594,2.9098,0.303387,0.147456,0.461186,6.783416,0.926482,0.046328,...,0.066317,0.009953,0.000219,0.01585,0.216445,0.000934,0.00363,0.050464,0.005334,0.026021
117,51.342188,23.52228,6.885258,10.52074,0.840864,0.253969,1.609749,12.076073,1.528521,0.067639,...,0.098527,0.016203,0.000335,0.022254,0.30574,0.001263,0.004089,0.072937,0.012678,0.056507
118,25.183548,8.681636,3.999339,4.48193,0.461759,0.152837,0.611879,5.587498,0.80137,0.050518,...,0.063956,0.009542,0.000213,0.013141,0.18366,0.000754,0.002029,0.048584,0.008394,0.035853
119,40.63167,17.451068,6.876217,8.63805,0.637753,0.181847,1.194083,7.97571,0.974742,0.046947,...,0.064847,0.010919,0.000315,0.014687,0.197723,0.000957,0.001841,0.051031,0.009856,0.041874
120,22.18462,7.221746,2.13206,3.02077,0.208007,0.157467,0.486471,7.261148,0.797955,0.040061,...,0.04962,0.007964,0.000267,0.021163,0.228257,0.001353,0.016515,0.122019,0.005382,0.034081

In [7]:
R1

,Date_Time,PM2.5,NO3-,SO42-,NH4+,K+,Na+,Cl-,OC,EC,...,Ca,Ti,V,Mn,Fe,Ni,Cu,Zn,As,Pb
0,11/16/19,7.650,-1.4300,-0.0978,-0.4110,0.09860,0.0274,0.0833,-1.4800,-0.0212,...,0.00233,0.000288,0.000430,-0.001910,0.03040,-0.000121,0.001750,-0.00810,-0.000984,-0.001140
1,11/19/19,0.522,0.2460,-0.1480,-0.0489,-0.05980,0.0509,0.0270,-2.5300,-0.3160,...,0.06750,0.003150,0.000202,0.001560,0.01570,0.000119,-0.000116,0.00419,0.000836,0.004150
2,11/22/19,8.330,1.6500,0.0628,0.3130,0.05000,-0.1050,-0.1030,-1.5400,0.3910,...,0.13000,0.004590,0.000129,-0.004200,0.08140,-0.000622,0.001390,-0.01330,-0.000715,-0.000922
3,11/26/19,5.230,-0.7410,0.0170,-0.1550,-0.02880,-0.0587,0.1640,-0.4280,0.4230,...,0.00382,0.000058,0.000252,-0.001440,0.00303,-0.000026,0.000584,-0.00535,0.000908,0.004460
4,11/30/19,7.590,0.0991,-0.1980,-0.1310,-0.08230,-0.1080,0.2310,-1.2600,-0.1610,...,0.01460,0.002280,0.001100,0.001410,0.07880,0.000634,-0.000695,0.00660,0.004720,0.040400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,11/24/20,-4.200,0.5660,-0.0386,-0.0968,-0.00804,-0.0106,0.0160,-0.9440,0.0710,...,0.00799,0.000088,-0.000011,0.007900,0.05070,0.000310,-0.000408,0.01350,0.000922,0.002470
117,11/26/20,-8.610,9.3500,-0.0242,0.3850,-0.08750,-0.0331,-0.0884,-1.5100,0.0477,...,-0.00777,0.001130,-0.000017,0.008750,0.06810,-0.000203,-0.000238,0.02240,0.008310,-0.010900
118,11/30/20,-5.300,2.1100,-0.1970,-0.0311,-0.04440,0.0306,-0.0473,0.0498,0.0819,...,0.00153,-0.003020,0.000006,0.003790,0.00861,0.000056,-0.000053,-0.00235,0.005340,0.000699
119,2012-02-20,-23.400,13.8000,1.2400,3.3800,-0.11200,0.0886,2.0700,-1.9300,-0.0299,...,0.06120,-0.000737,0.000035,-0.000078,-0.00772,-0.000237,0.000035,-0.00133,-0.000840,-0.009760
120,2012-06-20,20.600,-0.8570,0.2720,-0.3890,0.19600,0.1570,-0.0586,2.7200,0.1240,...,-0.00222,-0.000709,-0.000167,-0.003390,-0.01150,-0.000193,0.003540,0.00489,-0.001370,0.001690

In [8]:
X.iloc[:,1:]

,PM2.5,NO3-,SO42-,NH4+,K+,Na+,Cl-,OC,EC,Mg,...,Ca,Ti,V,Mn,Fe,Ni,Cu,Zn,As,Pb
0,36.186500,10.519697,3.070176,4.615067,0.292758,0.194727,0.845747,9.247382,1.177020,0.032839,...,0.067338,0.011543,0.000854,0.020004,0.304653,0.001473,0.008279,0.054187,0.000712,0.013999
1,13.795987,1.650593,1.645891,0.998299,0.099412,0.187291,0.116985,3.331602,0.528025,0.159301,...,0.134763,0.012723,0.000492,0.017377,0.235235,0.001179,0.001668,0.046186,0.004331,0.021339
2,31.454419,8.268086,1.724467,2.844703,0.270033,0.105607,0.315484,9.912487,1.908402,0.095912,...,0.233437,0.020110,0.000555,0.022091,0.443069,0.001095,0.005328,0.047591,0.002543,0.019609
3,25.748086,6.717402,1.969101,2.914216,0.191162,0.085555,0.657704,7.052623,1.331131,0.034988,...,0.061571,0.009189,0.000513,0.016355,0.224539,0.001116,0.008133,0.063110,0.004803,0.027526
4,40.446304,13.521696,1.797991,4.768353,0.415744,0.139027,1.138951,11.429528,1.536803,0.055017,...,0.127842,0.019549,0.001409,0.029095,0.457959,0.002170,0.006560,0.090531,0.012667,0.082001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,15.595000,7.345296,1.999587,2.823678,0.295429,0.136830,0.478906,5.845661,0.997388,0.036978,...,0.074426,0.010044,0.000209,0.023733,0.267098,0.001243,0.003228,0.063949,0.006267,0.028517
117,42.746000,32.898342,6.857061,10.924650,0.752566,0.220794,1.523791,10.588990,1.576165,0.060638,...,0.090983,0.017350,0.000319,0.031003,0.374063,0.001060,0.003854,0.095318,0.020996,0.045648
118,19.903000,10.806479,3.800149,4.462531,0.416710,0.183477,0.565980,5.650279,0.883609,0.075732,...,0.065652,0.006529,0.000219,0.016922,0.192359,0.000810,0.001979,0.046228,0.013736,0.036560
119,17.280000,31.231501,8.116521,12.034841,0.525552,0.270551,3.265267,6.061994,0.944623,0.053326,...,0.126237,0.010200,0.000350,0.014614,0.190218,0.000721,0.001875,0.049732,0.009036,0.032173
120,42.781000,6.381265,2.403858,2.640202,0.404271,0.314088,0.429149,9.980422,0.920737,0.025749,...,0.047424,0.007249,0.000101,0.017768,0.216489,0.001159,0.020082,0.127073,0.004022,0.035777

In [9]:
G2.iloc[:,1:] @ P3.T.iloc[1:,0:]/100

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,NaN,11.95234,3.171533,5.02888,0.194469,0.167465,0.76351,10.738999,1.194825,0.033364,...,0.065037,0.011247,0.000424,0.021943,0.274403,0.001596,0.006522,0.062249,0.001697,0.015138
1,NaN,1.406109,1.794086,1.047412,0.159512,0.13652,0.090169,5.865766,0.842245,0.047338,...,0.067263,0.009576,0.00029,0.015843,0.219812,0.001062,0.001783,0.042002,0.003492,0.017228
2,NaN,6.609243,1.661403,2.52986,0.220086,0.210525,0.418387,11.447023,1.511188,0.062893,...,0.102897,0.015499,0.000426,0.0263,0.361634,0.001719,0.003926,0.060881,0.00325,0.020525
3,NaN,7.454776,1.952472,3.068672,0.220316,0.144235,0.494308,7.479938,0.904866,0.038361,...,0.05773,0.009121,0.000261,0.017818,0.221507,0.001143,0.007551,0.068463,0.003898,0.023106
4,NaN,13.379562,1.991425,4.886436,0.49773,0.246647,0.906589,12.678478,1.690686,0.0739,...,0.113128,0.017243,0.000308,0.027692,0.379076,0.001537,0.007238,0.083832,0.007929,0.041554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,NaN,6.773803,2.036586,2.918964,0.303418,0.14735,0.46309,6.791946,0.923514,0.046295,...,0.066402,0.009947,0.00022,0.015849,0.216419,0.000935,0.003632,0.050417,0.005331,0.026048
117,NaN,23.546643,6.883688,10.542096,0.84066,0.253796,1.613895,12.120154,1.525828,0.067701,...,0.098726,0.016212,0.000336,0.022269,0.306264,0.001265,0.004087,0.072876,0.012665,0.056555
118,NaN,8.678405,3.999401,4.487704,0.4609,0.152663,0.612481,5.597919,0.799004,0.050548,...,0.064057,0.00954,0.000213,0.013135,0.183741,0.000755,0.002026,0.048525,0.00838,0.035862
119,NaN,17.447051,6.880551,8.652676,0.63753,0.18173,1.19567,7.998216,0.972373,0.04705,...,0.064985,0.010925,0.000316,0.014687,0.198006,0.000958,0.001836,0.051009,0.009854,0.041934
120,NaN,7.230413,2.133702,3.028192,0.208024,0.157188,0.487836,7.26445,0.794456,0.039994,...,0.049612,0.007948,0.000268,0.021186,0.227866,0.001354,0.016525,0.122032,0.005384,0.0341

In [10]:
P3.loc[0] = 100
P3

   species   Factor 1   Factor 2    Factor 3   Factor 4    Factor 5
0      100  100.00000  100.00000  100.000000  100.00000  100.000000
1     NO3-    0.00000    5.29000    0.000000    7.85000   73.200000
2    SO42-    6.01000    2.67000   21.600000   41.10000    5.300000
3     NH4+    0.00000    0.00000    9.320000   20.80000   26.000000
4       K+    0.00000    0.00000    4.300000    0.00000    1.420000
5      Na+    0.98000    1.37000    1.030000    0.32300    0.281000
6      Cl-    0.24600    0.02260    0.684000    0.33900    4.900000
7       OC   20.60000   77.70000    2.380000    8.81000   27.600000
8       EC    0.11300   10.30000    3.230000    0.00000    2.810000
9       Mg    0.23300    0.42200    0.545000    0.03750    0.000000
10      Si    0.15800    2.65000    2.280000    0.08680    0.343000
11      Ca    0.00000    0.71500    0.517000    0.02500    0.078400
12      Ti    0.00000    0.10500    0.060500    0.00865    0.020400
13       V    0.00115    0.00341    0.000000    0.00288    0.000000
14      Mn    0.18500    0.19400    0.053000    0.03540    0.026200
15      Fe    1.18000    2.64000    0.935000    0.29000    0.347000
16      Ni    0.01150    0.01350    0.000507    0.00610    0.000959
17      Cu    0.32100    0.02840    0.000000    0.00000    0.010800
18      Zn    2.01000    0.41300    0.361000    0.15200    0.048700
19      As    0.05900    0.00000    0.101000    0.00407    0.009730
20      Pb    0.43100    0.05570    0.392000    0.00652    0.058200

In [11]:
G2.iloc[:,1:] @ P3.T.iloc[1:,0:]/100

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,28.551,11.95234,3.171533,5.02888,0.194469,0.167465,0.76351,10.738999,1.194825,0.033364,...,0.065037,0.011247,0.000424,0.021943,0.274403,0.001596,0.006522,0.062249,0.001697,0.015138
1,13.2823,1.406109,1.794086,1.047412,0.159512,0.13652,0.090169,5.865766,0.842245,0.047338,...,0.067263,0.009576,0.00029,0.015843,0.219812,0.001062,0.001783,0.042002,0.003492,0.017228
2,23.1111,6.609243,1.661403,2.52986,0.220086,0.210525,0.418387,11.447023,1.511188,0.062893,...,0.102897,0.015499,0.000426,0.0263,0.361634,0.001719,0.003926,0.060881,0.00325,0.020525
3,20.52,7.454776,1.952472,3.068672,0.220316,0.144235,0.494308,7.479938,0.904866,0.038361,...,0.05773,0.009121,0.000261,0.017818,0.221507,0.001143,0.007551,0.068463,0.003898,0.023106
4,32.804,13.379562,1.991425,4.886436,0.49773,0.246647,0.906589,12.678478,1.690686,0.0739,...,0.113128,0.017243,0.000308,0.027692,0.379076,0.001537,0.007238,0.083832,0.007929,0.041554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,19.791,6.773803,2.036586,2.918964,0.303418,0.14735,0.46309,6.791946,0.923514,0.046295,...,0.066402,0.009947,0.00022,0.015849,0.216419,0.000935,0.003632,0.050417,0.005331,0.026048
117,51.3742,23.546643,6.883688,10.542096,0.84066,0.253796,1.613895,12.120154,1.525828,0.067701,...,0.098726,0.016212,0.000336,0.022269,0.306264,0.001265,0.004087,0.072876,0.012665,0.056555
118,25.1833,8.678405,3.999401,4.487704,0.4609,0.152663,0.612481,5.597919,0.799004,0.050548,...,0.064057,0.00954,0.000213,0.013135,0.183741,0.000755,0.002026,0.048525,0.00838,0.035862
119,40.646,17.447051,6.880551,8.652676,0.63753,0.18173,1.19567,7.998216,0.972373,0.04705,...,0.064985,0.010925,0.000316,0.014687,0.198006,0.000958,0.001836,0.051009,0.009854,0.041934
120,22.2,7.230413,2.133702,3.028192,0.208024,0.157188,0.487836,7.26445,0.794456,0.039994,...,0.049612,0.007948,0.000268,0.021186,0.227866,0.001354,0.016525,0.122032,0.005384,0.0341

In [12]:
G2.sum(axis=1) # row sum

0      28.5510
1      13.2823
2      23.1111
3      20.5200
4      32.8040
        ...
116    19.7910
117    51.3742
118    25.1833
119    40.6460
120    22.2000
Length: 121, dtype: float64

In [13]:
G1.sum(axis=1)

0       5.7350
1       3.4716
2       5.3073
3       5.1960
4       8.0650
        ...
116     4.9160
117    11.0401
118     6.0951
119     8.4730
120     6.9540
Length: 121, dtype: float64

P3 rescale for source sum = 100

P4 is recaled P matrix,
G3 is also recaled G matrix for P

In [14]:
scaling_factor = P3.T.iloc[1:,0:].sum(axis=1)-100
print(scaling_factor)

Factor 1     32.538650
Factor 2    104.592610
Factor 3     47.789007
Factor 4     79.876920
Factor 5    142.454389
dtype: float64

In [15]:
P4 = P3.iloc[1:,1:]/scaling_factor
P4

    Factor 1  Factor 2  Factor 3  Factor 4  Factor 5
1   0.000000  0.050577  0.000000  0.098276  0.513849
2   0.184703  0.025528  0.451987  0.514542  0.037205
3   0.000000  0.000000  0.195024  0.260401  0.182515
4   0.000000  0.000000  0.089979  0.000000  0.009968
5   0.030118  0.013098  0.021553  0.004044  0.001973
6   0.007560  0.000216  0.014313  0.004244  0.034397
7   0.633093  0.742882  0.049802  0.110295  0.193746
8   0.003473  0.098477  0.067589  0.000000  0.019726
9   0.007161  0.004035  0.011404  0.000469  0.000000
10  0.004856  0.025336  0.047710  0.001087  0.002408
11  0.000000  0.006836  0.010818  0.000313  0.000550
12  0.000000  0.001004  0.001266  0.000108  0.000143
13  0.000035  0.000033  0.000000  0.000036  0.000000
14  0.005686  0.001855  0.001109  0.000443  0.000184
15  0.036265  0.025241  0.019565  0.003631  0.002436
16  0.000353  0.000129  0.000011  0.000076  0.000007
17  0.009865  0.000272  0.000000  0.000000  0.000076
18  0.061773  0.003949  0.007554  0.001903  0.000342
19  0.001813  0.000000  0.002113  0.000051  0.000068
20  0.013246  0.000533  0.008203  0.000082  0.000409

In [16]:
P4.sum(axis=0)

Factor 1    1.0
Factor 2    1.0
Factor 3    1.0
Factor 4    1.0
Factor 5    1.0
dtype: float64

In [17]:
G3 = G2.iloc[:,1:]*scaling_factor/100
G3

     Factor 1   Factor 2  Factor 3  Factor 4   Factor 5
0    0.275928   7.949038 -0.237511  4.313354  21.653067
1   -0.028536   7.122757  1.581816  1.629489   1.723698
2   -0.027300  12.237335  1.170831  0.770812  11.510315
3    0.501095   5.794431  0.936665  1.517661  13.647130
4    0.258357  10.229157  2.738310 -0.958523  25.214427
..        ...        ...       ...       ...        ...
116  0.120718   5.512031  1.992802  0.990474  12.450514
117 -0.024664   3.577067  4.434820  6.110584  44.303315
118  0.010835   2.614815  3.354788  3.538548  15.954892
119 -0.089807   0.995722  3.502934  7.939766  32.337146
120  1.441462   4.779882  0.841087  1.693391  13.276749

[121 rows x 5 columns]

In [18]:
G3 @P4.T

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,11.952340,3.171533,5.028880,0.194469,0.167465,0.763510,10.738999,1.194825,0.033364,0.248231,0.065037,0.011247,0.000424,0.021943,0.274403,0.001596,0.006522,0.062249,0.001697,0.015138
1,1.406109,1.794086,1.047412,0.159512,0.136520,0.090169,5.865766,0.842245,0.047338,0.261715,0.067263,0.009576,0.000290,0.015843,0.219812,0.001062,0.001783,0.042002,0.003492,0.017228
2,6.609243,1.661403,2.529860,0.220086,0.210525,0.418387,11.447023,1.511188,0.062893,0.394329,0.102897,0.015499,0.000426,0.026300,0.361634,0.001719,0.003926,0.060881,0.003250,0.020525
3,7.454776,1.952472,3.068672,0.220316,0.144235,0.494308,7.479938,0.904866,0.038361,0.228440,0.057730,0.009121,0.000261,0.017818,0.221507,0.001143,0.007551,0.068463,0.003898,0.023106
4,13.379562,1.991425,4.886436,0.497730,0.246647,0.906589,12.678478,1.690686,0.073900,0.450738,0.113128,0.017243,0.000308,0.027692,0.379076,0.001537,0.007238,0.083832,0.007929,0.041554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,6.773803,2.036586,2.918964,0.303418,0.147350,0.463090,6.791946,0.923514,0.046295,0.266372,0.066402,0.009947,0.000220,0.015849,0.216419,0.000935,0.003632,0.050417,0.005331,0.026048
117,23.546643,6.883688,10.542096,0.840660,0.253796,1.613895,12.120154,1.525828,0.067701,0.415407,0.098725,0.016212,0.000336,0.022269,0.306264,0.001265,0.004087,0.072876,0.012665,0.056555
118,8.678405,3.999401,4.487704,0.460900,0.152663,0.612481,5.597919,0.799004,0.050548,0.268620,0.064057,0.009540,0.000213,0.013135,0.183741,0.000755,0.002026,0.048525,0.008380,0.035862
119,17.447051,6.880551,8.652676,0.637530,0.181730,1.195670,7.998216,0.972373,0.047050,0.278405,0.064985,0.010925,0.000316,0.014687,0.198007,0.000958,0.001836,0.051009,0.009854,0.041934
120,7.230413,2.133702,3.028192,0.208024,0.157188,0.487836,7.264450,0.794456,0.039994,0.202040,0.049612,0.007948,0.000268,0.021186,0.227866,0.001354,0.016525,0.122032,0.005384,0.034100

In [19]:
X

,date,PM2.5,NO3-,SO42-,NH4+,K+,Na+,Cl-,OC,EC,...,Ca,Ti,V,Mn,Fe,Ni,Cu,Zn,As,Pb
0,11/16/2019,36.186500,10.519697,3.070176,4.615067,0.292758,0.194727,0.845747,9.247382,1.177020,...,0.067338,0.011543,0.000854,0.020004,0.304653,0.001473,0.008279,0.054187,0.000712,0.013999
1,11/19/2019,13.795987,1.650593,1.645891,0.998299,0.099412,0.187291,0.116985,3.331602,0.528025,...,0.134763,0.012723,0.000492,0.017377,0.235235,0.001179,0.001668,0.046186,0.004331,0.021339
2,11/22/2019,31.454419,8.268086,1.724467,2.844703,0.270033,0.105607,0.315484,9.912487,1.908402,...,0.233437,0.020110,0.000555,0.022091,0.443069,0.001095,0.005328,0.047591,0.002543,0.019609
3,11/26/2019,25.748086,6.717402,1.969101,2.914216,0.191162,0.085555,0.657704,7.052623,1.331131,...,0.061571,0.009189,0.000513,0.016355,0.224539,0.001116,0.008133,0.063110,0.004803,0.027526
4,11/30/2019,40.446304,13.521696,1.797991,4.768353,0.415744,0.139027,1.138951,11.429528,1.536803,...,0.127842,0.019549,0.001409,0.029095,0.457959,0.002170,0.006560,0.090531,0.012667,0.082001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,11/24/2020,15.595000,7.345296,1.999587,2.823678,0.295429,0.136830,0.478906,5.845661,0.997388,...,0.074426,0.010044,0.000209,0.023733,0.267098,0.001243,0.003228,0.063949,0.006267,0.028517
117,11/26/2020,42.746000,32.898342,6.857061,10.924650,0.752566,0.220794,1.523791,10.588990,1.576165,...,0.090983,0.017350,0.000319,0.031003,0.374063,0.001060,0.003854,0.095318,0.020996,0.045648
118,11/30/2020,19.903000,10.806479,3.800149,4.462531,0.416710,0.183477,0.565980,5.650279,0.883609,...,0.065652,0.006529,0.000219,0.016922,0.192359,0.000810,0.001979,0.046228,0.013736,0.036560
119,12/2/2020,17.280000,31.231501,8.116521,12.034841,0.525552,0.270551,3.265267,6.061994,0.944623,...,0.126237,0.010200,0.000350,0.014614,0.190218,0.000721,0.001875,0.049732,0.009036,0.032173
120,12/6/2020,42.781000,6.381265,2.403858,2.640202,0.404271,0.314088,0.429149,9.980422,0.920737,...,0.047424,0.007249,0.000101,0.017768,0.216489,0.001159,0.020082,0.127073,0.004022,0.035777

In [20]:
G3.sum(axis=1)

0      33.953876
1      12.029224
2      25.661993
3      22.396982
4      37.481728
         ...
116    21.066538
117    58.401122
118    25.473878
119    44.685761
120    22.032571
Length: 121, dtype: float64